id: I9B307023
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T02:12:52+00:00'
last_modified: '2022-06-08T09:47:31.318990+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD222
  title: གངས་རིའི་བུ་ཕྲུག-པི་ཧྲི་ཞང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    6EAC:
      image_group_id: I2PD18814
      title: ''
      total_pages: 194
      order: 1
      base_file: 6EAC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
