id: P009265
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:30:40.916058
source_metadata:
  id: bdr:W3PD222
  title: གངས་རིའི་བུ་ཕྲུག-པི་ཧྲི་ཞང་།
  author: ''
  volumes:
    837b244a4c6a482e943940e6d2786821:
      image_group_id: I2PD18814
      title: ''
      volume_number: 1
      total_pages: 194
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
